insert into poopreporter_food (name) values ('Snack');
insert into poopreporter_food (name) values ('Okra');
insert into poopreporter_food (name) values ('GENERAL MILLS');
insert into poopreporter_food (name) values ('Bologna');
insert into poopreporter_food (name) values ('SILK Hazelnut Creamer');
insert into poopreporter_food (name) values ('Parsley');
insert into poopreporter_food (name) values ('ARCHWAY Home Style Cookies');
insert into poopreporter_food (name) values ('Sugar');
insert into poopreporter_food (name) values ('Clam and tomato juice');
insert into poopreporter_food (name) values ('Apricots');
insert into poopreporter_food (name) values ('Pork sausage rice links');
insert into poopreporter_food (name) values ('Applesauce');
insert into poopreporter_food (name) values ('Orange-strawberry-banana juice');
insert into poopreporter_food (name) values ('Animal fat');
insert into poopreporter_food (name) values ('Yogurt');
insert into poopreporter_food (name) values ('Split pea soup');
insert into poopreporter_food (name) values ('Carob flour');
insert into poopreporter_food (name) values ('Pokeberry shoots');
insert into poopreporter_food (name) values ('Plums');
insert into poopreporter_food (name) values ('Soy protein isolate');
insert into poopreporter_food (name) values ('WORTHINGTON Saucettes');
insert into poopreporter_food (name) values ('KELLOGG\'S Eggo Golden Oat Waffles');
insert into poopreporter_food (name) values ('Walrus');
insert into poopreporter_food (name) values ('Pretzels');
insert into poopreporter_food (name) values ('Kohlrabi');
insert into poopreporter_food (name) values ('WORTHINGTON Prosage Roll');
insert into poopreporter_food (name) values ('Lemon peel');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Breakfast Bacon Strips');
insert into poopreporter_food (name) values ('Agave');
insert into poopreporter_food (name) values ('Coffee substitute');
insert into poopreporter_food (name) values ('English muffins');
insert into poopreporter_food (name) values ('Molasses');
insert into poopreporter_food (name) values ('Elderberries');
insert into poopreporter_food (name) values ('HOT POCKETS Ham \'N Cheese Stuffed Sandwich');
insert into poopreporter_food (name) values ('Cream substitute');
insert into poopreporter_food (name) values ('Fruit-flavored drink mix');
insert into poopreporter_food (name) values ('CAMPBELL Soup Company');
insert into poopreporter_food (name) values ('GEORGE WESTON BAKERIES');
insert into poopreporter_food (name) values ('PIZZA HUT 14" Pepperoni Pizza');
insert into poopreporter_food (name) values ('Persimmons');
insert into poopreporter_food (name) values ('Water with added vitamins and minerals');
insert into poopreporter_food (name) values ('Cheese substitute');
insert into poopreporter_food (name) values ('ENSURE FIBER WITH FOS');
insert into poopreporter_food (name) values ('Cheese fondue');
insert into poopreporter_food (name) values ('MARTHA WHITE FOODS');
insert into poopreporter_food (name) values ('SILK Vanilla soy yogurt (single serving size)');
insert into poopreporter_food (name) values ('Hush puppies');
insert into poopreporter_food (name) values ('Pan Dulce');
insert into poopreporter_food (name) values ('Turkey breast meat');
insert into poopreporter_food (name) values ('Chicken breast');
insert into poopreporter_food (name) values ('STOUFFER\'S Lasagna with Meat & Sauce');
insert into poopreporter_food (name) values ('Salt');
insert into poopreporter_food (name) values ('Cloudberries');
insert into poopreporter_food (name) values ('Luxury loaf');
insert into poopreporter_food (name) values ('Plains Pricklypear');
insert into poopreporter_food (name) values ('Currants');
insert into poopreporter_food (name) values ('Vitasoy USA');
insert into poopreporter_food (name) values ('Kale');
insert into poopreporter_food (name) values ('Dulce de Leche');
insert into poopreporter_food (name) values ('Cereals ready-to-eat');
insert into poopreporter_food (name) values ('Bacon');
insert into poopreporter_food (name) values ('Bread stuffing');
insert into poopreporter_food (name) values ('Chicken patty');
insert into poopreporter_food (name) values ('Juice');
insert into poopreporter_food (name) values ('Fennel');
insert into poopreporter_food (name) values ('WORTHINGTON Choplets');
insert into poopreporter_food (name) values ('Tomato juice');
insert into poopreporter_food (name) values ('Chicken roll');
insert into poopreporter_food (name) values ('Muffin');
insert into poopreporter_food (name) values ('Noodles');
insert into poopreporter_food (name) values ('Yogurt parfait');
insert into poopreporter_food (name) values ('Turkey');
insert into poopreporter_food (name) values ('Brussels sprouts');
insert into poopreporter_food (name) values ('Rice drink');
insert into poopreporter_food (name) values ('Hearts of palm');
insert into poopreporter_food (name) values ('Pineapple juice');
insert into poopreporter_food (name) values ('Chili con carne with beans');
insert into poopreporter_food (name) values ('Willow');
insert into poopreporter_food (name) values ('Polish sausage');
insert into poopreporter_food (name) values ('Pumpkin leaves');
insert into poopreporter_food (name) values ('Lard');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Meal Starters Chik\'n Strips');
insert into poopreporter_food (name) values ('Shortening');
insert into poopreporter_food (name) values ('Chicory');
insert into poopreporter_food (name) values ('Peppers');
insert into poopreporter_food (name) values ('Cherries');
insert into poopreporter_food (name) values ('SILK Chai');
insert into poopreporter_food (name) values ('Mammy-apple');
insert into poopreporter_food (name) values ('Avocados');
insert into poopreporter_food (name) values ('Rice');
insert into poopreporter_food (name) values ('USDA Commodity Food');
insert into poopreporter_food (name) values ('Cheesecake commercially prepared');
insert into poopreporter_food (name) values ('PIZZA HUT 12" Pepperoni Pizza');
insert into poopreporter_food (name) values ('STAGG Classic Chili with Beans');
insert into poopreporter_food (name) values ('Stew/soup');
insert into poopreporter_food (name) values ('Beverages');
insert into poopreporter_food (name) values ('Tamarinds');
insert into poopreporter_food (name) values ('Squash');
insert into poopreporter_food (name) values ('Shortening frying (heavy duty)');
insert into poopreporter_food (name) values ('Reddi Wip Fat Free Whipped Topping');
insert into poopreporter_food (name) values ('Raspberries');
insert into poopreporter_food (name) values ('Gerber graduates Fruit Strips Real Fruit Bars');
insert into poopreporter_food (name) values ('HORMEL Roast Beef Hash');
insert into poopreporter_food (name) values ('MOR-NU');
insert into poopreporter_food (name) values ('Pimento');
insert into poopreporter_food (name) values ('MARIE CALLENDER\'S Beef Stroganoff and Noodles w/Carrots and Peas');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Garden Veggie Patties');
insert into poopreporter_food (name) values ('Ham salad spread');
insert into poopreporter_food (name) values ('Oven-roasted chicken breast roll');
insert into poopreporter_food (name) values ('Turkey and gravy');
insert into poopreporter_food (name) values ('INTERSTATE BRANDS CORP');
insert into poopreporter_food (name) values ('Potato chips');
insert into poopreporter_food (name) values ('Longans');
insert into poopreporter_food (name) values ('Ostrich');
insert into poopreporter_food (name) values ('Salad Dressing');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Italian Style Sausage');
insert into poopreporter_food (name) values ('Pork and turkey sausage');
insert into poopreporter_food (name) values ('Onion rings');
insert into poopreporter_food (name) values ('Winged beans');
insert into poopreporter_food (name) values ('Amaranth grain');
insert into poopreporter_food (name) values ('DOMINO\'S 14" EXTRAVAGANZZA FEAST Pizza');
insert into poopreporter_food (name) values ('Entrees');
insert into poopreporter_food (name) values ('Scrapple');
insert into poopreporter_food (name) values ('Bacon bits');
insert into poopreporter_food (name) values ('Margarine-like spread with yogurt');
insert into poopreporter_food (name) values ('WORTHINGTON Wham (roll)');
insert into poopreporter_food (name) values ('Chrysanthemum leaves');
insert into poopreporter_food (name) values ('Guanabana nectar');
insert into poopreporter_food (name) values ('KELLOGG\'S Eggo Lowfat Nutri-Grain Waffles');
insert into poopreporter_food (name) values ('Lettuce');
insert into poopreporter_food (name) values ('WORTHINGTON Chic-Ketts');
insert into poopreporter_food (name) values ('Candied fruit');
insert into poopreporter_food (name) values ('Pastry');
insert into poopreporter_food (name) values ('Turkey ham');
insert into poopreporter_food (name) values ('Spelt');
insert into poopreporter_food (name) values ('Onions');
insert into poopreporter_food (name) values ('SILK Vanilla');
insert into poopreporter_food (name) values ('Peanut spread');
insert into poopreporter_food (name) values ('Mutton');
insert into poopreporter_food (name) values ('Collards');
insert into poopreporter_food (name) values ('HORMEL Corned Beef Hash');
insert into poopreporter_food (name) values ('Spinach');
insert into poopreporter_food (name) values ('FREEZER QUEEN Gravy & Sliced Beef Meal');
insert into poopreporter_food (name) values ('Amaranth');
insert into poopreporter_food (name) values ('AMARANTH FLAKES');
insert into poopreporter_food (name) values ('Macaroni');
insert into poopreporter_food (name) values ('Piki bread');
insert into poopreporter_food (name) values ('Cranberry sauce');
insert into poopreporter_food (name) values ('BANQUET Salisbury Steak Meal');
insert into poopreporter_food (name) values ('Whey');
insert into poopreporter_food (name) values ('KRAFT CHEEZ WHIZ Pasteurized Process Cheese Sauce');
insert into poopreporter_food (name) values ('Coriander (cilantro) leaves');
insert into poopreporter_food (name) values ('LOMA LINDA Swiss Stake with Gravy');
insert into poopreporter_food (name) values ('Bulgur');
insert into poopreporter_food (name) values ('Rose-apples');
insert into poopreporter_food (name) values ('Toaster pastries');
insert into poopreporter_food (name) values ('Cheese product');
insert into poopreporter_food (name) values ('Groundcherries');
insert into poopreporter_food (name) values ('Chickpeas (garbanzo beans');
insert into poopreporter_food (name) values ('Corn');
insert into poopreporter_food (name) values ('WORTHINGTON Veja-Links');
insert into poopreporter_food (name) values ('Peas');
insert into poopreporter_food (name) values ('Soy meal');
insert into poopreporter_food (name) values ('Salami');
insert into poopreporter_food (name) values ('Arrowroot');
insert into poopreporter_food (name) values ('Peanut butter');
insert into poopreporter_food (name) values ('Shallots');
insert into poopreporter_food (name) values ('Taco shells');
insert into poopreporter_food (name) values ('LOMA LINDA Vege-Burger');
insert into poopreporter_food (name) values ('Lotus root');
insert into poopreporter_food (name) values ('Stew');
insert into poopreporter_food (name) values ('Butter');
insert into poopreporter_food (name) values ('Butter oil');
insert into poopreporter_food (name) values ('Puddings');
insert into poopreporter_food (name) values ('Eggnog');
insert into poopreporter_food (name) values ('Cocktail mix');
insert into poopreporter_food (name) values ('Passion-fruit juice');
insert into poopreporter_food (name) values ('Thyme');
insert into poopreporter_food (name) values ('Spinach souffle');
insert into poopreporter_food (name) values ('Zwieback');
insert into poopreporter_food (name) values ('Fish broth');
insert into poopreporter_food (name) values ('Soursop');
insert into poopreporter_food (name) values ('Beverage');
insert into poopreporter_food (name) values ('Burrito');
insert into poopreporter_food (name) values ('Bockwurst');
insert into poopreporter_food (name) values ('Vital wheat gluten');
insert into poopreporter_food (name) values ('Sour cream');
insert into poopreporter_food (name) values ('WORTHINGTON Low Fat Fri Chik');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Mesquite Chicken BBQ');
insert into poopreporter_food (name) values ('Sweeteners');
insert into poopreporter_food (name) values ('LITTLE CAESARS 14" Pepperoni Pizza');
insert into poopreporter_food (name) values ('Cheese');
insert into poopreporter_food (name) values ('Pasta with Sliced Franks in Tomato Sauce');
insert into poopreporter_food (name) values ('SILK Nog');
insert into poopreporter_food (name) values ('Litchis');
insert into poopreporter_food (name) values ('WORTHINGTON FriChik Original');
insert into poopreporter_food (name) values ('Quinces');
insert into poopreporter_food (name) values ('LOUIS RICH');
insert into poopreporter_food (name) values ('STOUFFER\'S Stuffed Peppers with Beef in Tomato Sauce');
insert into poopreporter_food (name) values ('Kielbasa');
insert into poopreporter_food (name) values ('Ham and cheese loaf or roll');
insert into poopreporter_food (name) values ('WORTHINGTON Multigrain Cutlets');
insert into poopreporter_food (name) values ('Sandwich spread');
insert into poopreporter_food (name) values ('Luncheon slices');
insert into poopreporter_food (name) values ('Hyacinth beans');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Asian Veggie Patties');
insert into poopreporter_food (name) values ('Wheat flour');
insert into poopreporter_food (name) values ('Tennis Bread');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS America\'s Original Veggie Dog');
insert into poopreporter_food (name) values ('STOUFFER\'S LEAN CUISINE Chicken Enchilada Suiza with Sour Cream Sauce and Mexican-Style Rice');
insert into poopreporter_food (name) values ('PIZZA HUT 14" Super Supreme Pizza');
insert into poopreporter_food (name) values ('HORMEL SPAM');
insert into poopreporter_food (name) values ('Rowal');
insert into poopreporter_food (name) values ('Pizza');
insert into poopreporter_food (name) values ('Veal');
insert into poopreporter_food (name) values ('Cocoa');
insert into poopreporter_food (name) values ('Moose');
insert into poopreporter_food (name) values ('LITTLE CAESARS 14" Original Round Meat and Vegetable Pizza');
insert into poopreporter_food (name) values ('Mustard');
insert into poopreporter_food (name) values ('Cauliflower');
insert into poopreporter_food (name) values ('Sweet potato leaves');
insert into poopreporter_food (name) values ('Gelatin desserts');
insert into poopreporter_food (name) values ('Popcorn');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Ginger Teriyaki Veggie Cakes');
insert into poopreporter_food (name) values ('Lima beans');
insert into poopreporter_food (name) values ('Wild rice');
insert into poopreporter_food (name) values ('Fruit');
insert into poopreporter_food (name) values ('Figs');
insert into poopreporter_food (name) values ('Barley malt flour');
insert into poopreporter_food (name) values ('Taro shoots');
insert into poopreporter_food (name) values ('Frozen novelites');
insert into poopreporter_food (name) values ('KRAFT VELVEETA Pasteurized Process Cheese Spread');
insert into poopreporter_food (name) values ('Cabbage');
insert into poopreporter_food (name) values ('Pitanga');
insert into poopreporter_food (name) values ('Agutuk');
insert into poopreporter_food (name) values ('Babyfood');
insert into poopreporter_food (name) values ('Vinegar');
insert into poopreporter_food (name) values ('Swisswurst');
insert into poopreporter_food (name) values ('Tomato powder');
insert into poopreporter_food (name) values ('Fruit salad');
insert into poopreporter_food (name) values ('SILK Blueberry soy Yogurt');
insert into poopreporter_food (name) values ('Baby food');
insert into poopreporter_food (name) values ('Pie crust');
insert into poopreporter_food (name) values ('Cheese spread');
insert into poopreporter_food (name) values ('Peppermint');
insert into poopreporter_food (name) values ('Alcoholic Beverage');
insert into poopreporter_food (name) values ('WORTHINGTON Vegetable Steaks');
insert into poopreporter_food (name) values ('Sauerkraut');
insert into poopreporter_food (name) values ('CRACKER BARREL');
insert into poopreporter_food (name) values ('Tangerines');
insert into poopreporter_food (name) values ('USDA Commodity peaches');
insert into poopreporter_food (name) values ('Liver sausage');
insert into poopreporter_food (name) values ('Wheat germ');
insert into poopreporter_food (name) values ('Egg substitute');
insert into poopreporter_food (name) values ('MCKEE BAKING');
insert into poopreporter_food (name) values ('Limeade');
insert into poopreporter_food (name) values ('Tapioca');
insert into poopreporter_food (name) values ('Margarine-like');
insert into poopreporter_food (name) values ('Bananas');
insert into poopreporter_food (name) values ('Breadfruit');
insert into poopreporter_food (name) values ('Hummus');
insert into poopreporter_food (name) values ('Sherbet');
insert into poopreporter_food (name) values ('Bison');
insert into poopreporter_food (name) values ('Pigeonpeas');
insert into poopreporter_food (name) values ('Carrot juice');
insert into poopreporter_food (name) values ('Gelatins');
insert into poopreporter_food (name) values ('OSCAR MAYER. Bologna (Wisconsin made ring)');
insert into poopreporter_food (name) values ('Chewing gum');
insert into poopreporter_food (name) values ('Seal');
insert into poopreporter_food (name) values ('HORMEL Chili with Beans');
insert into poopreporter_food (name) values ('Milk shakes');
insert into poopreporter_food (name) values ('Veggie burgers or soyburgers');
insert into poopreporter_food (name) values ('Peas and onions');
insert into poopreporter_food (name) values ('LOMA LINDA Big Franks');
insert into poopreporter_food (name) values ('KRAFT');
insert into poopreporter_food (name) values ('Blueberries');
insert into poopreporter_food (name) values ('KELLOGG\'S Eggo Lowfat Homestyle Waffles');
insert into poopreporter_food (name) values ('Plantains');
insert into poopreporter_food (name) values ('Custard-apple');
insert into poopreporter_food (name) values ('Buckwheat flour');
insert into poopreporter_food (name) values ('WORTHINGTON Meatless Chicken Roll');
insert into poopreporter_food (name) values ('Pate de foie gras');
insert into poopreporter_food (name) values ('Soy sauce made from soy (tamari)');
insert into poopreporter_food (name) values ('BURGER KING');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Grillers Burger Style Recipe Crumbles');
insert into poopreporter_food (name) values ('Liver cheese');
insert into poopreporter_food (name) values ('POPEYES');
insert into poopreporter_food (name) values ('Apricot nectar');
insert into poopreporter_food (name) values ('Parsnips');
insert into poopreporter_food (name) values ('Dessert topping');
insert into poopreporter_food (name) values ('Fast Foods');
insert into poopreporter_food (name) values ('Potato pancakes');
insert into poopreporter_food (name) values ('Energy Drink');
insert into poopreporter_food (name) values ('Sorghum');
insert into poopreporter_food (name) values ('Raisins');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Chicken Teriyaki w/Rice Medley Broccoli');
insert into poopreporter_food (name) values ('Rambutan');
insert into poopreporter_food (name) values ('Turkey bacon');
insert into poopreporter_food (name) values ('Pate');
insert into poopreporter_food (name) values ('DOMINO\'S 14" Cheese Pizza');
insert into poopreporter_food (name) values ('Acerola juice');
insert into poopreporter_food (name) values ('Croissants');
insert into poopreporter_food (name) values ('KRAFT BREAKSTONE\'S FREE Fat Free Sour Cream');
insert into poopreporter_food (name) values ('Broccoli');
insert into poopreporter_food (name) values ('Prunes');
insert into poopreporter_food (name) values ('Pear nectar');
insert into poopreporter_food (name) values ('STAGG Ranchhouse Chili with Beans');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Maple Flavored Veggie Sausage Patties');
insert into poopreporter_food (name) values ('Meat drippings (lard');
insert into poopreporter_food (name) values ('LOMA LINDA Redi-Burger');
insert into poopreporter_food (name) values ('Mother\'s loaf');
insert into poopreporter_food (name) values ('Leavening agents');
insert into poopreporter_food (name) values ('Wheat bran');
insert into poopreporter_food (name) values ('KRAFT BREYERS LIGHT Nonfat Strawberry Yogurt (with Aspartame and Fructose Sweeteners)');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Corn Dogs made w/ Natural Ingredients');
insert into poopreporter_food (name) values ('Tortilla');
insert into poopreporter_food (name) values ('SILK Plus Omega-3 DHA');
insert into poopreporter_food (name) values ('Turkey roast');
insert into poopreporter_food (name) values ('PAPA JOHN\'S 14" Pepperoni Pizza');
insert into poopreporter_food (name) values ('Ice creams');
insert into poopreporter_food (name) values ('Whale');
insert into poopreporter_food (name) values ('Chayote');
insert into poopreporter_food (name) values ('Incaparina');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Mushroom Lover\'s Burger');
insert into poopreporter_food (name) values ('Goose');
insert into poopreporter_food (name) values ('Mulberries');
insert into poopreporter_food (name) values ('Frankfurter');
insert into poopreporter_food (name) values ('Quail');
insert into poopreporter_food (name) values ('Pickles');
insert into poopreporter_food (name) values ('Spaghetti');
insert into poopreporter_food (name) values ('Milk');
insert into poopreporter_food (name) values ('Barley');
insert into poopreporter_food (name) values ('Potatoes');
insert into poopreporter_food (name) values ('MISSION FOODS');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Breakfast Sausage Links');
insert into poopreporter_food (name) values ('Vegetarian meatloaf or patties');
insert into poopreporter_food (name) values ('Jerusalem-artichokes');
insert into poopreporter_food (name) values ('Tomato and vegetable juice');
insert into poopreporter_food (name) values ('Shortening bread');
insert into poopreporter_food (name) values ('MARIE CALLENDER\'S Chicken Pot Pie');
insert into poopreporter_food (name) values ('Tostada shells');
insert into poopreporter_food (name) values ('Wheat');
insert into poopreporter_food (name) values ('Butterbur');
insert into poopreporter_food (name) values ('Java-plum');
insert into poopreporter_food (name) values ('Couscous');
insert into poopreporter_food (name) values ('CARL BUDDIG. Cooked Smoked Beef Pastrami');
insert into poopreporter_food (name) values ('Puff pastry');
insert into poopreporter_food (name) values ('Braunschweiger (a liver sausage)');
insert into poopreporter_food (name) values ('Edamame');
insert into poopreporter_food (name) values ('Eppaw');
insert into poopreporter_food (name) values ('Gravy');
insert into poopreporter_food (name) values ('Macaroni and cheese dinner with dry sauce mix');
insert into poopreporter_food (name) values ('Cake');
insert into poopreporter_food (name) values ('Fruit cocktail');
insert into poopreporter_food (name) values ('USDA Commodity pears');
insert into poopreporter_food (name) values ('Turkey and pork sausage');
insert into poopreporter_food (name) values ('WORTHINGTON Stripples');
insert into poopreporter_food (name) values ('Egg Mix');
insert into poopreporter_food (name) values ('WORTHINGTON FriPats');
insert into poopreporter_food (name) values ('McDONALD\'S');
insert into poopreporter_food (name) values ('Croutons');
insert into poopreporter_food (name) values ('Waxgourd');
insert into poopreporter_food (name) values ('Fiddlehead ferns');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Corn Dogs');
insert into poopreporter_food (name) values ('Watermelon');
insert into poopreporter_food (name) values ('Corn with red and green peppers');
insert into poopreporter_food (name) values ('Fish sticks');
insert into poopreporter_food (name) values ('Flan');
insert into poopreporter_food (name) values ('WORTHINGTON Vegetable Skallops');
insert into poopreporter_food (name) values ('WORTHINGTON Stakelets');
insert into poopreporter_food (name) values ('Pineapple and orange juice drink');
insert into poopreporter_food (name) values ('Ham and cheese spread');
insert into poopreporter_food (name) values ('Luncheon meat');
insert into poopreporter_food (name) values ('HORMEL ALWAYS TENDER');
insert into poopreporter_food (name) values ('Citrus fruit juice drink');
insert into poopreporter_food (name) values ('Tamales (Navajo)');
insert into poopreporter_food (name) values ('Pummelo');
insert into poopreporter_food (name) values ('Strudel');
insert into poopreporter_food (name) values ('Lemonade-flavor drink');
insert into poopreporter_food (name) values ('Frog legs');
insert into poopreporter_food (name) values ('Loquats');
insert into poopreporter_food (name) values ('Rennin');
insert into poopreporter_food (name) values ('Falafel');
insert into poopreporter_food (name) values ('Nopales');
insert into poopreporter_food (name) values ('Beans');
insert into poopreporter_food (name) values ('Milk substitutes');
insert into poopreporter_food (name) values ('Buckwheat');
insert into poopreporter_food (name) values ('Rice cake');
insert into poopreporter_food (name) values ('QUAKER OATS');
insert into poopreporter_food (name) values ('Egg');
insert into poopreporter_food (name) values ('New england brand sausage');
insert into poopreporter_food (name) values ('HEINZ');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Southwest Veggie Cakes');
insert into poopreporter_food (name) values ('Grape drink');
insert into poopreporter_food (name) values ('Vegetable juice cocktail');
insert into poopreporter_food (name) values ('Beef sausage');
insert into poopreporter_food (name) values ('Candies');
insert into poopreporter_food (name) values ('Pie Crust');
insert into poopreporter_food (name) values ('Coffeecake');
insert into poopreporter_food (name) values ('Doughnuts');
insert into poopreporter_food (name) values ('Liverwurst spread');
insert into poopreporter_food (name) values ('Mouse nuts');
insert into poopreporter_food (name) values ('Mushrooms');
insert into poopreporter_food (name) values ('LITTLE CAESARS 14" Original Round Pepperoni Pizza');
insert into poopreporter_food (name) values ('Keikitos (muffins)');
insert into poopreporter_food (name) values ('Seaweed');
insert into poopreporter_food (name) values ('Frozen novelties');
insert into poopreporter_food (name) values ('CHEF BOYARDEE Beef Ravioli in Tomato and Meat Sauce');
insert into poopreporter_food (name) values ('Beef stew');
insert into poopreporter_food (name) values ('Chicken nuggets');
insert into poopreporter_food (name) values ('Lamb');
insert into poopreporter_food (name) values ('Grapefruit juice');
insert into poopreporter_food (name) values ('Turkey patties');
insert into poopreporter_food (name) values ('PAPA JOHN\'S 14" Cheese Pizza');
insert into poopreporter_food (name) values ('Rice noodles');
insert into poopreporter_food (name) values ('Restaurant');
insert into poopreporter_food (name) values ('Mountain yam');
insert into poopreporter_food (name) values ('Danish pastry');
insert into poopreporter_food (name) values ('HORMEL WRANGLER Beef Franks');
insert into poopreporter_food (name) values ('Yachtwurst');
insert into poopreporter_food (name) values ('Potato flour');
insert into poopreporter_food (name) values ('Yam');
insert into poopreporter_food (name) values ('Chrysanthemum');
insert into poopreporter_food (name) values ('Bacon and beef sticks');
insert into poopreporter_food (name) values ('Turkey Pot Pie');
insert into poopreporter_food (name) values ('USDA Commodity');
insert into poopreporter_food (name) values ('Chorizo');
insert into poopreporter_food (name) values ('Kumquats');
insert into poopreporter_food (name) values ('Turkey breast');
insert into poopreporter_food (name) values ('HORMEL');
insert into poopreporter_food (name) values ('Tomatoes');
insert into poopreporter_food (name) values ('Pineapple and grapefruit juice drink');
insert into poopreporter_food (name) values ('Lime juice');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Bites Spinach Artichoke');
insert into poopreporter_food (name) values ('Vanilla extract');
insert into poopreporter_food (name) values ('Feijoa');
insert into poopreporter_food (name) values ('Orange peel');
insert into poopreporter_food (name) values ('Chocolate syrup');
insert into poopreporter_food (name) values ('OSCAR MAYER');
insert into poopreporter_food (name) values ('Epazote');
insert into poopreporter_food (name) values ('Garlic');
insert into poopreporter_food (name) values ('Cereals ready to eat');
insert into poopreporter_food (name) values ('Borage');
insert into poopreporter_food (name) values ('KRAFT BREAKSTONE\'S Reduced Fat Sour Cream');
insert into poopreporter_food (name) values ('Watercress');
insert into poopreporter_food (name) values ('Dove');
insert into poopreporter_food (name) values ('Vegetables');
insert into poopreporter_food (name) values ('Vegetable oil-butter spread');
insert into poopreporter_food (name) values ('Tangerine juice');
insert into poopreporter_food (name) values ('Chicken breast tenders');
insert into poopreporter_food (name) values ('Orange breakfast drink');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Meatless Mini Corn Dogs');
insert into poopreporter_food (name) values ('Mustard greens');
insert into poopreporter_food (name) values ('Yardlong beans');
insert into poopreporter_food (name) values ('Buckwheat groats');
insert into poopreporter_food (name) values ('Refried beans');
insert into poopreporter_food (name) values ('Melons');
insert into poopreporter_food (name) values ('Cheese sauce');
insert into poopreporter_food (name) values ('Artichokes');
insert into poopreporter_food (name) values ('Bean beverage');
insert into poopreporter_food (name) values ('Radish seeds');
insert into poopreporter_food (name) values ('Eggplant');
insert into poopreporter_food (name) values ('Arrowroot flour');
insert into poopreporter_food (name) values ('Game meat');
insert into poopreporter_food (name) values ('KENTUCKY FRIED CHICKEN');
insert into poopreporter_food (name) values ('Orange drink');
insert into poopreporter_food (name) values ('Chili');
insert into poopreporter_food (name) values ('HORMEL Pillow Pak Sliced Turkey Pepperoni');
insert into poopreporter_food (name) values ('SILK Plain');
insert into poopreporter_food (name) values ('LITTLE CAESARS 14" Original Round Cheese Pizza');
insert into poopreporter_food (name) values ('Tamarind nectar');
insert into poopreporter_food (name) values ('Corn beverage');
insert into poopreporter_food (name) values ('Grape juice');
insert into poopreporter_food (name) values ('Jellies');
insert into poopreporter_food (name) values ('Duck');
insert into poopreporter_food (name) values ('Stinging Nettles');
insert into poopreporter_food (name) values ('Amaranth leaves');
insert into poopreporter_food (name) values ('Lentils');
insert into poopreporter_food (name) values ('Olives');
insert into poopreporter_food (name) values ('Balsam-pear (bitter gourd)');
insert into poopreporter_food (name) values ('Cranberry juice cocktail');
insert into poopreporter_food (name) values ('KEEBLER');
insert into poopreporter_food (name) values ('PEPPERIDGE FARM Crusty Italian Bread');
insert into poopreporter_food (name) values ('Soy sauce made from soy and wheat (shoyu)');
insert into poopreporter_food (name) values ('Steelhead trout');
insert into poopreporter_food (name) values ('Waffles');
insert into poopreporter_food (name) values ('Celery');
insert into poopreporter_food (name) values ('Brotwurst');
insert into poopreporter_food (name) values ('PIZZA HUT 12" Super Supreme Pizza');
insert into poopreporter_food (name) values ('Nectarines');
insert into poopreporter_food (name) values ('SILK Original Creamer');
insert into poopreporter_food (name) values ('Millet');
insert into poopreporter_food (name) values ('Burdock root');
insert into poopreporter_food (name) values ('Fruit punch-flavor drink');
insert into poopreporter_food (name) values ('Apple cider-flavored drink');
insert into poopreporter_food (name) values ('Chives');
insert into poopreporter_food (name) values ('Oil');
insert into poopreporter_food (name) values ('Cranberry-apricot juice drink');
insert into poopreporter_food (name) values ('SILK Plus for Bone Health');
insert into poopreporter_food (name) values ('NABISCO');
insert into poopreporter_food (name) values ('NESTLE');
insert into poopreporter_food (name) values ('PAPA JOHN\'S 14" The Works Pizza');
insert into poopreporter_food (name) values ('Dandelion greens');
insert into poopreporter_food (name) values ('Cheesefurter');
insert into poopreporter_food (name) values ('Rutabagas');
insert into poopreporter_food (name) values ('Dock');
insert into poopreporter_food (name) values ('Cherimoya');
insert into poopreporter_food (name) values ('Carrot');
insert into poopreporter_food (name) values ('Corn bran');
insert into poopreporter_food (name) values ('Winged bean leaves');
insert into poopreporter_food (name) values ('Formulated bar');
insert into poopreporter_food (name) values ('Turnip greens');
insert into poopreporter_food (name) values ('Oheloberries');
insert into poopreporter_food (name) values ('Poultry');
insert into poopreporter_food (name) values ('Dill weed');
insert into poopreporter_food (name) values ('Tortellini');
insert into poopreporter_food (name) values ('Vinespinach');
insert into poopreporter_food (name) values ('SILK Banana-Strawberry soy Yogurt');
insert into poopreporter_food (name) values ('Sea lion');
insert into poopreporter_food (name) values ('Sea cucumber');
insert into poopreporter_food (name) values ('McDONALD\'S Bacon Ranch Salad with Crispy Chicken');
insert into poopreporter_food (name) values ('Wine');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Grillers Prime');
insert into poopreporter_food (name) values ('Rice flour');
insert into poopreporter_food (name) values ('Pepperoni');
insert into poopreporter_food (name) values ('Peach nectar');
insert into poopreporter_food (name) values ('Margarine');
insert into poopreporter_food (name) values ('Butter replacement');
insert into poopreporter_food (name) values ('HOT POCKETS');
insert into poopreporter_food (name) values ('Rosemary');
insert into poopreporter_food (name) values ('SILK Very Vanilla');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Traditional Meat Loaf w/Brown Sauce');
insert into poopreporter_food (name) values ('Child formula');
insert into poopreporter_food (name) values ('Chicken spread');
insert into poopreporter_food (name) values ('Teff');
insert into poopreporter_food (name) values ('Turnip greens and turnips');
insert into poopreporter_food (name) values ('Lemonade');
insert into poopreporter_food (name) values ('Hazelnuts');
insert into poopreporter_food (name) values ('Yellow pond lily');
insert into poopreporter_food (name) values ('Arugula');
insert into poopreporter_food (name) values ('Phyllo dough');
insert into poopreporter_food (name) values ('Side dishes');
insert into poopreporter_food (name) values ('Rice bran');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS BBQ Riblets');
insert into poopreporter_food (name) values ('Poi');
insert into poopreporter_food (name) values ('Cowpeas (Blackeyes)');
insert into poopreporter_food (name) values ('WORTHINGTON Smoked Turkey Roll');
insert into poopreporter_food (name) values ('Artificial Blueberry Muffin Mix');
insert into poopreporter_food (name) values ('Leeks');
insert into poopreporter_food (name) values ('Cassava');
insert into poopreporter_food (name) values ('Drink mix');
insert into poopreporter_food (name) values ('Fast foods');
insert into poopreporter_food (name) values ('Taro');
insert into poopreporter_food (name) values ('Ham');
insert into poopreporter_food (name) values ('Whipped topping');
insert into poopreporter_food (name) values ('Eclairs');
insert into poopreporter_food (name) values ('CARL BUDDIG');
insert into poopreporter_food (name) values ('Guavas');
insert into poopreporter_food (name) values ('Melon');
insert into poopreporter_food (name) values ('Sugar-apples');
insert into poopreporter_food (name) values ('Baked beans');
insert into poopreporter_food (name) values ('Carambola');
insert into poopreporter_food (name) values ('Yautia (tannier)');
insert into poopreporter_food (name) values ('Pork and beef sausage');
insert into poopreporter_food (name) values ('SILK French Vanilla Creamer');
insert into poopreporter_food (name) values ('Macaroni and Cheese');
insert into poopreporter_food (name) values ('RED BARON Premium Pockets');
insert into poopreporter_food (name) values ('HORMEL Chili');
insert into poopreporter_food (name) values ('SILK Mocha');
insert into poopreporter_food (name) values ('Rice and Wheat cereal bar');
insert into poopreporter_food (name) values ('Bratwurst');
insert into poopreporter_food (name) values ('Potato soup');
insert into poopreporter_food (name) values ('Capers');
insert into poopreporter_food (name) values ('Spearmint');
insert into poopreporter_food (name) values ('BANQUET Chicken Pot pie');
insert into poopreporter_food (name) values ('BANQUET Original Fried Chicken Thigh Meal');
insert into poopreporter_food (name) values ('BUTCHER BOY MEATS');
insert into poopreporter_food (name) values ('Thuringer');
insert into poopreporter_food (name) values ('Oat bran');
insert into poopreporter_food (name) values ('Corn pudding');
insert into poopreporter_food (name) values ('Cheesecake prepared from mix');
insert into poopreporter_food (name) values ('French toast');
insert into poopreporter_food (name) values ('Toppings');
insert into poopreporter_food (name) values ('WENDY\'S');
insert into poopreporter_food (name) values ('Grape juice cocktail');
insert into poopreporter_food (name) values ('Pumpkin flowers');
insert into poopreporter_food (name) values ('Hyacinth-beans');
insert into poopreporter_food (name) values ('Bread sticks');
insert into poopreporter_food (name) values ('Rice bowl with chicken');
insert into poopreporter_food (name) values ('Turkey sticks');
insert into poopreporter_food (name) values ('Frostings');
insert into poopreporter_food (name) values ('Cereals');
insert into poopreporter_food (name) values ('Orange-grapefruit juice');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Chik\'n Nuggets');
insert into poopreporter_food (name) values ('Parmesan cheese topping');
insert into poopreporter_food (name) values ('Soymilk');
insert into poopreporter_food (name) values ('Mortadella');
insert into poopreporter_food (name) values ('Celeriac');
insert into poopreporter_food (name) values ('Milk dessert');
insert into poopreporter_food (name) values ('BANQUET Turkey and Gravy w/Dressing Meal');
insert into poopreporter_food (name) values ('Papaya nectar');
insert into poopreporter_food (name) values ('Triticale');
insert into poopreporter_food (name) values ('Lasagna with meat & sauce');
insert into poopreporter_food (name) values ('WORTHINGTON Super Links');
insert into poopreporter_food (name) values ('Salmonberries');
insert into poopreporter_food (name) values ('Dairy drink mix');
insert into poopreporter_food (name) values ('Huckleberries');
insert into poopreporter_food (name) values ('Cranberry juice');
insert into poopreporter_food (name) values ('Beef Macaroni');
insert into poopreporter_food (name) values ('Dates');
insert into poopreporter_food (name) values ('WORTHINGTON Meatless Corned Beef Roll');
insert into poopreporter_food (name) values ('SILK Plain soy yogurt');
insert into poopreporter_food (name) values ('Game meat ');
insert into poopreporter_food (name) values ('Wonton wrappers (includes egg roll wrappers)');
insert into poopreporter_food (name) values ('Pasta with meatballs in tomato sauce');
insert into poopreporter_food (name) values ('Peppered loaf');
insert into poopreporter_food (name) values ('STOUFFER\'S LEAN CUISINE Swedish Meatballs with Pasta');
insert into poopreporter_food (name) values ('Cowpeas');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Country Roasted Turkey w/Cranberry Apple Sauce');
insert into poopreporter_food (name) values ('Peas and carrots');
insert into poopreporter_food (name) values ('Cheese puffs and twists');
insert into poopreporter_food (name) values ('Buffalo');
insert into poopreporter_food (name) values ('PILLSBURY');
insert into poopreporter_food (name) values ('Water');
insert into poopreporter_food (name) values ('Horseradish-tree');
insert into poopreporter_food (name) values ('Pectin');
insert into poopreporter_food (name) values ('Orange and apricot juice drink');
insert into poopreporter_food (name) values ('Waterchestnuts');
insert into poopreporter_food (name) values ('Poultry salad sandwich spread');
insert into poopreporter_food (name) values ('Jellyfish');
insert into poopreporter_food (name) values ('Spaghetti with meat sauce');
insert into poopreporter_food (name) values ('SILK Peach soy Yogurt');
insert into poopreporter_food (name) values ('Frijoles rojos volteados (Refried beans');
insert into poopreporter_food (name) values ('Oats');
insert into poopreporter_food (name) values ('Mangos');
insert into poopreporter_food (name) values ('Tortilla chips');
insert into poopreporter_food (name) values ('Soy sauce made from hydrolyzed vegetable protein');
insert into poopreporter_food (name) values ('Chokecherries');
insert into poopreporter_food (name) values ('MORI-NU');
insert into poopreporter_food (name) values ('Mustard spinach');
insert into poopreporter_food (name) values ('Shortening cake mix');
insert into poopreporter_food (name) values ('Protein supplement');
insert into poopreporter_food (name) values ('KRAFT CHEEZ WHIZ LIGHT Pasteurized Process Cheese Product');
insert into poopreporter_food (name) values ('STOUFFER\'S Chicken Pie');
insert into poopreporter_food (name) values ('WORTHINGTON Dinner Roast');
insert into poopreporter_food (name) values ('Pumpkin pie mix');
insert into poopreporter_food (name) values ('Margarine-like spread');
insert into poopreporter_food (name) values ('Octopus (Alaska Native)');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Grillers Vegan');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Sausage Style Recipe Crumbles');
insert into poopreporter_food (name) values ('Pickle relish');
insert into poopreporter_food (name) values ('New zealand spinach');
insert into poopreporter_food (name) values ('KRAFT BREYERS LIGHT N\' LIVELY Lowfat Strawberry Yogurt (1%% Milkfat)');
insert into poopreporter_food (name) values ('Adobo fresco');
insert into poopreporter_food (name) values ('WORTHINGTON Vegetarian Burger');
insert into poopreporter_food (name) values ('Fish');
insert into poopreporter_food (name) values ('OLD EL PASO Chili with Beans');
insert into poopreporter_food (name) values ('Guava nectar');
insert into poopreporter_food (name) values ('Cockles');
insert into poopreporter_food (name) values ('Baking chocolate');
insert into poopreporter_food (name) values ('Kiwifruit');
insert into poopreporter_food (name) values ('Caribou');
insert into poopreporter_food (name) values ('KRAFT FREE Singles American Nonfat Pasteurized Process Cheese Product');
insert into poopreporter_food (name) values ('Strawberry-flavor beverage mix');
insert into poopreporter_food (name) values ('Pudding');
insert into poopreporter_food (name) values ('Scrambled Eggs & Sausage with Hashed Brown Potatoes');
insert into poopreporter_food (name) values ('SILK Light Vanilla');
insert into poopreporter_food (name) values ('Mixed vegetable and fruit juice drink');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Original Chik\'n Tenders');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Bites Broccoli Cheddar');
insert into poopreporter_food (name) values ('Cranberry-apple juice drink');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Mesquite Beef w/BBQ Sauce');
insert into poopreporter_food (name) values ('Abiyuch');
insert into poopreporter_food (name) values ('KRAFT VELVEETA LIGHT Reduced Fat Pasteurized Process Cheese Product');
insert into poopreporter_food (name) values ('Cornmeal');
insert into poopreporter_food (name) values ('Sausage');
insert into poopreporter_food (name) values ('Pears');
insert into poopreporter_food (name) values ('Milk and cereal bar');
insert into poopreporter_food (name) values ('Infant formula');
insert into poopreporter_food (name) values ('Jujube');
insert into poopreporter_food (name) values ('Mayonnaise');
insert into poopreporter_food (name) values ('Chocolate');
insert into poopreporter_food (name) values ('PILLSBURY Golden Layer Buttermilk Biscuits');
insert into poopreporter_food (name) values ('Bread crumbs');
insert into poopreporter_food (name) values ('Apple juice');
insert into poopreporter_food (name) values ('Oat flour');
insert into poopreporter_food (name) values ('Turnips');
insert into poopreporter_food (name) values ('Quinoa');
insert into poopreporter_food (name) values ('Soy protein concentrate');
insert into poopreporter_food (name) values ('Split pea with ham soup');
insert into poopreporter_food (name) values ('Cornstarch');
insert into poopreporter_food (name) values ('STOUFFER\'S LEAN CUISINE Spaghetti with Meat Sauce');
insert into poopreporter_food (name) values ('Gooseberries');
insert into poopreporter_food (name) values ('Salmon');
insert into poopreporter_food (name) values ('Oranges');
insert into poopreporter_food (name) values ('Meat extender');
insert into poopreporter_food (name) values ('Energy drink');
insert into poopreporter_food (name) values ('Infant Formula');
insert into poopreporter_food (name) values ('Prairie Turnips');
insert into poopreporter_food (name) values ('Vegetarian stew');
insert into poopreporter_food (name) values ('Mung beans');
insert into poopreporter_food (name) values ('Shortening confectionery');
insert into poopreporter_food (name) values ('Palm hearts');
insert into poopreporter_food (name) values ('PATIO Beef and Bean Burrito');
insert into poopreporter_food (name) values ('LEAN POCKETS');
insert into poopreporter_food (name) values ('Passion-fruit');
insert into poopreporter_food (name) values ('Soymilk (all flavors)');
insert into poopreporter_food (name) values ('PEPPERIDGE FARM Classic Style Croutons');
insert into poopreporter_food (name) values ('Emu');
insert into poopreporter_food (name) values ('KRAFT BREYERS Smooth & Creamy Lowfat Strawberry Yogurt (1%% Milkfat)');
insert into poopreporter_food (name) values ('KID CUISINE Chicken Nuggets w/Pasta in Cheese Sauce');
insert into poopreporter_food (name) values ('Pigeon peas (red gram)');
insert into poopreporter_food (name) values ('Lean Pockets');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Salisbury Steak w/Mushroom Gravy');
insert into poopreporter_food (name) values ('WORTHINGTON Diced Chik');
insert into poopreporter_food (name) values ('Pomegranates');
insert into poopreporter_food (name) values ('Broadbeans');
insert into poopreporter_food (name) values ('Miso');
insert into poopreporter_food (name) values ('Radicchio');
insert into poopreporter_food (name) values ('Pork sausage');
insert into poopreporter_food (name) values ('SILK Vanilla soy Yogurt (Family size)');
insert into poopreporter_food (name) values ('Popovers');
insert into poopreporter_food (name) values ('Breakfast tart');
insert into poopreporter_food (name) values ('Wheat flours');
insert into poopreporter_food (name) values ('Carrots');
insert into poopreporter_food (name) values ('Potato salad');
insert into poopreporter_food (name) values ('Frybread');
insert into poopreporter_food (name) values ('Lambs quarters');
insert into poopreporter_food (name) values ('Marmalade');
insert into poopreporter_food (name) values ('LOMA LINDA Tender Rounds with Gravy');
insert into poopreporter_food (name) values ('HORMEL Canadian Style Bacon');
insert into poopreporter_food (name) values ('DENNY\'S');
insert into poopreporter_food (name) values ('Acorn stew (Apache)');
insert into poopreporter_food (name) values ('Orange-flavor drink');
insert into poopreporter_food (name) values ('MARIE CALLENDER\'S Turkey w/Gravy and Dressing with Mashed Potatoes');
insert into poopreporter_food (name) values ('SILK Strawberry soy yogurt');
insert into poopreporter_food (name) values ('Eggnog-flavor mix');
insert into poopreporter_food (name) values ('Bagels');
insert into poopreporter_food (name) values ('LOMA LINDA Linketts');
insert into poopreporter_food (name) values ('Smoked link sausage');
insert into poopreporter_food (name) values ('Beef Pot Pie');
insert into poopreporter_food (name) values ('Cream puffs');
insert into poopreporter_food (name) values ('Celtuce');
insert into poopreporter_food (name) values ('Tomato sauce');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Spicy Black Bean Burger');
insert into poopreporter_food (name) values ('KELLOGG\'S Eggo Lowfat Blueberry Nutri-Grain Waffles');
insert into poopreporter_food (name) values ('SILK Unsweetened');
insert into poopreporter_food (name) values ('Soy flour');
insert into poopreporter_food (name) values ('Smelt');
insert into poopreporter_food (name) values ('Barley flour or meal');
insert into poopreporter_food (name) values ('Squirrel');
insert into poopreporter_food (name) values ('KELLOGG');
insert into poopreporter_food (name) values ('Vermicelli');
insert into poopreporter_food (name) values ('Bear');
insert into poopreporter_food (name) values ('Breakfast Burrito');
insert into poopreporter_food (name) values ('Strawberries');
insert into poopreporter_food (name) values ('Chilchen (Red Berry Beverage) (Navajo)');
insert into poopreporter_food (name) values ('Lemons');
insert into poopreporter_food (name) values ('Pasta');
insert into poopreporter_food (name) values ('CONTINENTAL MILLS');
insert into poopreporter_food (name) values ('Guinea hen');
insert into poopreporter_food (name) values ('Chard');
insert into poopreporter_food (name) values ('WORTHINGTON Low Fat Veja-Links');
insert into poopreporter_food (name) values ('Knackwurst');
insert into poopreporter_food (name) values ('Ice cream cones');
insert into poopreporter_food (name) values ('Shortening household soybean (hydrogenated) and palm');
insert into poopreporter_food (name) values ('Orange juice');
insert into poopreporter_food (name) values ('Tempeh');
insert into poopreporter_food (name) values ('Hominy');
insert into poopreporter_food (name) values ('Honey roll sausage');
insert into poopreporter_food (name) values ('Corn flour');
insert into poopreporter_food (name) values ('Fungi');
insert into poopreporter_food (name) values ('Yambean (jicama)');
insert into poopreporter_food (name) values ('Soup');
insert into poopreporter_food (name) values ('Coffee and cocoa (mocha) powder');
insert into poopreporter_food (name) values ('Lasagna');
insert into poopreporter_food (name) values ('Bamboo shoots');
insert into poopreporter_food (name) values ('STOUFFER\'S LEAN CUISINE Chicken and Vegetables with Vermicelli');
insert into poopreporter_food (name) values ('Pineapple');
insert into poopreporter_food (name) values ('GARDENBURGER');
insert into poopreporter_food (name) values ('Turkey sausage');
insert into poopreporter_food (name) values ('Jams and preserves');
insert into poopreporter_food (name) values ('Chocolate-flavored drink');
insert into poopreporter_food (name) values ('Lupins');
insert into poopreporter_food (name) values ('Chicken pot pie');
insert into poopreporter_food (name) values ('Owl');
insert into poopreporter_food (name) values ('Pork');
insert into poopreporter_food (name) values ('THE BUDGET GOURMET');
insert into poopreporter_food (name) values ('Fruit butters');
insert into poopreporter_food (name) values ('Snacks');
insert into poopreporter_food (name) values ('Chickpea flour (besan)');
insert into poopreporter_food (name) values ('Mayonnaise dressing');
insert into poopreporter_food (name) values ('Headcheese');
insert into poopreporter_food (name) values ('Carbonated beverage');
insert into poopreporter_food (name) values ('Rolls');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Meal Starters Steak Strips');
insert into poopreporter_food (name) values ('STOUFFER\'S LEAN CUISINE Spaghetti with Meatballs and Sauce');
insert into poopreporter_food (name) values ('SILK Light Plain');
insert into poopreporter_food (name) values ('SILK Chocolate');
insert into poopreporter_food (name) values ('LOMA LINDA Low Fat Big Franks');
insert into poopreporter_food (name) values ('BETTY CROCKER');
insert into poopreporter_food (name) values ('Clementines');
insert into poopreporter_food (name) values ('Cattail');
insert into poopreporter_food (name) values ('Taro leaves');
insert into poopreporter_food (name) values ('Gourd');
insert into poopreporter_food (name) values ('Nuts');
insert into poopreporter_food (name) values ('Broadbeans (fava beans)');
insert into poopreporter_food (name) values ('Malt beverage');
insert into poopreporter_food (name) values ('Oopah (tunicate)');
insert into poopreporter_food (name) values ('WORTHINGTON Chili');
insert into poopreporter_food (name) values ('SILK Black Cherry soy Yogurt');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Chik Patties');
insert into poopreporter_food (name) values ('Fluid replacement');
insert into poopreporter_food (name) values ('Pumpkin');
insert into poopreporter_food (name) values ('Chocolate-flavor beverage mix for milk');
insert into poopreporter_food (name) values ('TYSON Chicken Fajita Kit');
insert into poopreporter_food (name) values ('Cheese food');
insert into poopreporter_food (name) values ('Fruit punch drink');
insert into poopreporter_food (name) values ('Pinon Nuts');
insert into poopreporter_food (name) values ('HEALTHY CHOICE Chicken Enchilada Suprema in Green Chili Sauce');
insert into poopreporter_food (name) values ('Eggs');
insert into poopreporter_food (name) values ('Breakfast type drink');
insert into poopreporter_food (name) values ('Fat');
insert into poopreporter_food (name) values ('Alcoholic beverage');
insert into poopreporter_food (name) values ('Salad dressing');
insert into poopreporter_food (name) values ('Grape juice drink');
insert into poopreporter_food (name) values ('Winged bean');
insert into poopreporter_food (name) values ('Carissa');
insert into poopreporter_food (name) values ('Cereal ready-to-eat');
insert into poopreporter_food (name) values ('Beet greens');
insert into poopreporter_food (name) values ('Mothbeans');
insert into poopreporter_food (name) values ('Rye flour');
insert into poopreporter_food (name) values ('Creamy dressing');
insert into poopreporter_food (name) values ('Sapote');
insert into poopreporter_food (name) values ('Lambsquarters');
insert into poopreporter_food (name) values ('Ready-to-drink reduced fat milk beverage');
insert into poopreporter_food (name) values ('Sourdock');
insert into poopreporter_food (name) values ('Potato');
insert into poopreporter_food (name) values ('Goat');
insert into poopreporter_food (name) values ('Egg rolls');
insert into poopreporter_food (name) values ('HORMEL Turkey Chili with Beans');
insert into poopreporter_food (name) values ('SILK Light Chocolate');
insert into poopreporter_food (name) values ('Grape leaves');
insert into poopreporter_food (name) values ('Mungo beans');
insert into poopreporter_food (name) values ('KRAFT FOODS');
insert into poopreporter_food (name) values ('Blood sausage');
insert into poopreporter_food (name) values ('Sweet potato');
insert into poopreporter_food (name) values ('Mangosteen');
insert into poopreporter_food (name) values ('Blackberry juice');
insert into poopreporter_food (name) values ('Cookies');
insert into poopreporter_food (name) values ('DOMINO\'S 14" Pepperoni Pizza');
insert into poopreporter_food (name) values ('Pheasant');
insert into poopreporter_food (name) values ('Sweet rolls');
insert into poopreporter_food (name) values ('Soybeans');
insert into poopreporter_food (name) values ('Tomatillos');
insert into poopreporter_food (name) values ('Poultry food products');
insert into poopreporter_food (name) values ('Chicory greens');
insert into poopreporter_food (name) values ('Swamp cabbage');
insert into poopreporter_food (name) values ('Pie');
insert into poopreporter_food (name) values ('Turkey thigh');
insert into poopreporter_food (name) values ('Honey');
insert into poopreporter_food (name) values ('Loganberries');
insert into poopreporter_food (name) values ('SILK Coffee');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Grillers Original');
insert into poopreporter_food (name) values ('Cranberry-grape juice drink');
insert into poopreporter_food (name) values ('Barbecue loaf');
insert into poopreporter_food (name) values ('Muffins');
insert into poopreporter_food (name) values ('Fish oil');
insert into poopreporter_food (name) values ('CHEF BOYARDEE Spaghetti and Meatballs in tomato Sauce');
insert into poopreporter_food (name) values ('PEPPERIDGE FARM Apple Turnovers');
insert into poopreporter_food (name) values ('Peanut flour');
insert into poopreporter_food (name) values ('PIZZA HUT 12" Cheese Pizza');
insert into poopreporter_food (name) values ('Arrowhead');
insert into poopreporter_food (name) values ('Beef');
insert into poopreporter_food (name) values ('Rhubarb');
insert into poopreporter_food (name) values ('Turkey roll');
insert into poopreporter_food (name) values ('Corned beef loaf');
insert into poopreporter_food (name) values ('Meatballs');
insert into poopreporter_food (name) values ('Salsify');
insert into poopreporter_food (name) values ('Basil');
insert into poopreporter_food (name) values ('Grapefruit');
insert into poopreporter_food (name) values ('HORMEL Vegetarian Chili with Beans');
insert into poopreporter_food (name) values ('Sapodilla');
insert into poopreporter_food (name) values ('Peanuts');
insert into poopreporter_food (name) values ('Margarine-like vegetable-oil spread');
insert into poopreporter_food (name) values ('Pickle and pimiento loaf');
insert into poopreporter_food (name) values ('Papad');
insert into poopreporter_food (name) values ('Broccoli raab');
insert into poopreporter_food (name) values ('Granola bar');
insert into poopreporter_food (name) values ('Coffee');
insert into poopreporter_food (name) values ('Deer (venison)');
insert into poopreporter_food (name) values ('Pastrami');
insert into poopreporter_food (name) values ('Catsup');
insert into poopreporter_food (name) values ('Desserts');
insert into poopreporter_food (name) values ('Potato puffs');
insert into poopreporter_food (name) values ('Campbell\'s V8 100%% Vegetable Juice');
insert into poopreporter_food (name) values ('STAGG Dynamite Chili with Beans');
insert into poopreporter_food (name) values ('Wasabi');
insert into poopreporter_food (name) values ('Chicory roots');
insert into poopreporter_food (name) values ('Yardlong bean');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Breakfast Pattie made with Organic Soy');
insert into poopreporter_food (name) values ('Vegetarian fillets');
insert into poopreporter_food (name) values ('STAGG SILVERADO Chili with Beans');
insert into poopreporter_food (name) values ('Semolina');
insert into poopreporter_food (name) values ('Picnic loaf');
insert into poopreporter_food (name) values ('Tree fern');
insert into poopreporter_food (name) values ('Ginger root');
insert into poopreporter_food (name) values ('Guava sauce');
insert into poopreporter_food (name) values ('Jute');
insert into poopreporter_food (name) values ('Mashu roots');
insert into poopreporter_food (name) values ('Triticale flour');
insert into poopreporter_food (name) values ('Pepeao');
insert into poopreporter_food (name) values ('Cranberry');
insert into poopreporter_food (name) values ('TACO BELL');
insert into poopreporter_food (name) values ('Malabar spinach');
insert into poopreporter_food (name) values ('Pepper');
insert into poopreporter_food (name) values ('Tofu yogurt');
insert into poopreporter_food (name) values ('Peanut butter with omega-3');
insert into poopreporter_food (name) values ('Seeds');
insert into poopreporter_food (name) values ('Lemon grass (citronella)');
insert into poopreporter_food (name) values ('Whiskey sour mix');
insert into poopreporter_food (name) values ('Vegetable oil');
insert into poopreporter_food (name) values ('Turtle');
insert into poopreporter_food (name) values ('Carob-flavor beverage mix');
insert into poopreporter_food (name) values ('Coleslaw');
insert into poopreporter_food (name) values ('Breakfast bars');
insert into poopreporter_food (name) values ('Purslane');
insert into poopreporter_food (name) values ('Sugars');
insert into poopreporter_food (name) values ('Soymilk (All flavors)');
insert into poopreporter_food (name) values ('Horseradish-tree leafy tips');
insert into poopreporter_food (name) values ('Peaches');
insert into poopreporter_food (name) values ('Tomato products');
insert into poopreporter_food (name) values ('Lemon juice');
insert into poopreporter_food (name) values ('Shake');
insert into poopreporter_food (name) values ('Chili with beans');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Grillers Chik\'n Veggie Patties');
insert into poopreporter_food (name) values ('Durian');
insert into poopreporter_food (name) values ('Syrups');
insert into poopreporter_food (name) values ('Prune juice');
insert into poopreporter_food (name) values ('Elk');
insert into poopreporter_food (name) values ('Fruit-flavored drink');
insert into poopreporter_food (name) values ('KELLOGG\'S Pop-Tarts Pastry Swirls');
insert into poopreporter_food (name) values ('Roselle');
insert into poopreporter_food (name) values ('New Zealand spinach');
insert into poopreporter_food (name) values ('Natto');
insert into poopreporter_food (name) values ('T.G.I. FRIDAY\'S');
insert into poopreporter_food (name) values ('Chiton');
insert into poopreporter_food (name) values ('Horseradish');
insert into poopreporter_food (name) values ('Tostada with guacamole');
insert into poopreporter_food (name) values ('Cranberries');
insert into poopreporter_food (name) values ('WORTHINGTON Prime Stakes');
insert into poopreporter_food (name) values ('Dutch brand loaf');
insert into poopreporter_food (name) values ('Cress');
insert into poopreporter_food (name) values ('Sauce');
insert into poopreporter_food (name) values ('Fireweed');
insert into poopreporter_food (name) values ('USDA Commodity Chicken');
insert into poopreporter_food (name) values ('Rose Hips');
insert into poopreporter_food (name) values ('WORTHINGTON Leanies');
insert into poopreporter_food (name) values ('Pancakes');
insert into poopreporter_food (name) values ('Crustaceans');
insert into poopreporter_food (name) values ('Apples');
insert into poopreporter_food (name) values ('Beef broth and tomato juice');
insert into poopreporter_food (name) values ('Cardoon');
insert into poopreporter_food (name) values ('Sesbania flower');
insert into poopreporter_food (name) values ('Boysenberries');
insert into poopreporter_food (name) values ('Chocolate-flavored hazelnut spread');
insert into poopreporter_food (name) values ('Honey loaf');
insert into poopreporter_food (name) values ('Grapes');
insert into poopreporter_food (name) values ('LITTLE CAESARS 14" Cheese Pizza');
insert into poopreporter_food (name) values ('Cucumber');
insert into poopreporter_food (name) values ('Cocoa mix');
insert into poopreporter_food (name) values ('Toaster Pastries');
insert into poopreporter_food (name) values ('LIPTON');
insert into poopreporter_food (name) values ('BANQUET HEARTY ONES Salisbury Steak Dinner');
insert into poopreporter_food (name) values ('Bread');
insert into poopreporter_food (name) values ('Frozen yogurts');
insert into poopreporter_food (name) values ('Radishes');
insert into poopreporter_food (name) values ('Mollusks');
insert into poopreporter_food (name) values ('Limes');
insert into poopreporter_food (name) values ('Asparagus');
insert into poopreporter_food (name) values ('HODGSON MILL');
insert into poopreporter_food (name) values ('Melon balls');
insert into poopreporter_food (name) values ('GREEN GIANT');
insert into poopreporter_food (name) values ('Yeast extract spread');
insert into poopreporter_food (name) values ('Ascidians (tunughnak) (Alaska Native)');
insert into poopreporter_food (name) values ('Mango nectar');
insert into poopreporter_food (name) values ('Prune puree');
insert into poopreporter_food (name) values ('Light Ice Cream');
insert into poopreporter_food (name) values ('Spices');
insert into poopreporter_food (name) values ('Sandwiches and burgers');
insert into poopreporter_food (name) values ('BANQUET Sliced Beef Meal');
insert into poopreporter_food (name) values ('PIZZA HUT 14" Cheese Pizza');
insert into poopreporter_food (name) values ('Kamut');
insert into poopreporter_food (name) values ('Tea');
insert into poopreporter_food (name) values ('Kanpyo');
insert into poopreporter_food (name) values ('Orange juice drink');
insert into poopreporter_food (name) values ('Macaroni and cheese loaf');
insert into poopreporter_food (name) values ('KRAFT BREYERS Lowfat Strawberry Yogurt (1%% Milkfat)');
insert into poopreporter_food (name) values ('PILLSBURY GRANDS');
insert into poopreporter_food (name) values ('Sour dressing');
insert into poopreporter_food (name) values ('Corned beef and potatoes in tortilla (Apache)');
insert into poopreporter_food (name) values ('Tofu');
insert into poopreporter_food (name) values ('Fruit punch juice drink');
insert into poopreporter_food (name) values ('Cream');
insert into poopreporter_food (name) values ('Margarine-like shortening');
insert into poopreporter_food (name) values ('Jackfruit');
insert into poopreporter_food (name) values ('Sports drink');
insert into poopreporter_food (name) values ('Celery flakes');
insert into poopreporter_food (name) values ('Pomegranate juice');
insert into poopreporter_food (name) values ('Rye');
insert into poopreporter_food (name) values ('Cornsalad');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Tomato & Basil Pizza Burger');
insert into poopreporter_food (name) values ('SILK Raspberry soy yogurt');
insert into poopreporter_food (name) values ('Papayas');
insert into poopreporter_food (name) values ('Tortillas');
insert into poopreporter_food (name) values ('Chocolate-flavor beverage mix');
insert into poopreporter_food (name) values ('Squab');
insert into poopreporter_food (name) values ('Fast Food');
insert into poopreporter_food (name) values ('SILK Plus Fiber');
insert into poopreporter_food (name) values ('Maraschino cherries');
insert into poopreporter_food (name) values ('Luncheon sausage');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS MeatFree Buffalo Wings');
insert into poopreporter_food (name) values ('WORTHINGTON Prosage Links');
insert into poopreporter_food (name) values ('CHEF BOYARDEE Beefaroni');
insert into poopreporter_food (name) values ('Pancakes plain');
insert into poopreporter_food (name) values ('Egg custards');
insert into poopreporter_food (name) values ('Blackberries');
insert into poopreporter_food (name) values ('Crabapples');
insert into poopreporter_food (name) values ('CHEF BOYARDEE Mini Ravioli');
insert into poopreporter_food (name) values ('Roast beef spread');
insert into poopreporter_food (name) values ('STAGG Country Chili with Beans');
insert into poopreporter_food (name) values ('Margarine Spread');
insert into poopreporter_food (name) values ('Lebanon bologna');
insert into poopreporter_food (name) values ('Cowpeas (blackeyes)');
insert into poopreporter_food (name) values ('Beerwurst');
insert into poopreporter_food (name) values ('Pie fillings');
insert into poopreporter_food (name) values ('Alfalfa seeds');
insert into poopreporter_food (name) values ('Acerola');
insert into poopreporter_food (name) values ('APPLEBEE\'S');
insert into poopreporter_food (name) values ('Cranberry-orange relish');
insert into poopreporter_food (name) values ('Winged bean tuber');
insert into poopreporter_food (name) values ('Imitation cheese');
insert into poopreporter_food (name) values ('Beets');
insert into poopreporter_food (name) values ('STOUFFER\'S LEAN CUISINE Homestyle Stuffed Cabbage with Meat in Tomato Sauce and Whipped Potatoes');
insert into poopreporter_food (name) values ('Succotash');
insert into poopreporter_food (name) values ('Breakfast bar');
insert into poopreporter_food (name) values ('Mush');
insert into poopreporter_food (name) values ('Jew\'s ear');
insert into poopreporter_food (name) values ('Pasta with tomato sauce');
insert into poopreporter_food (name) values ('SILK Key Lime soy Yogurt');
insert into poopreporter_food (name) values ('Cracker meal');
insert into poopreporter_food (name) values ('Crackers');
insert into poopreporter_food (name) values ('Biscuits');
insert into poopreporter_food (name) values ('Endive');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Veggie Breakfast Sausage Patties');
insert into poopreporter_food (name) values ('LOMA LINDA Little Links');
insert into poopreporter_food (name) values ('LOMA LINDA Tender Bits');
insert into poopreporter_food (name) values ('WEIGHT WATCHERS SMART ONES');
insert into poopreporter_food (name) values ('Cereal wafer straws');
insert into poopreporter_food (name) values ('Shortening industrial');
insert into poopreporter_food (name) values ('GARDENBURGER Breaded Chik\'n Veggie Patties');
insert into poopreporter_food (name) values ('Waffle');
insert into poopreporter_food (name) values ('MORNINGSTAR FARMS Italian Herb Chik Patties');
insert into poopreporter_food (name) values ('Meal supplement drink');
insert into poopreporter_food (name) values ('Malted drink mix');
insert into poopreporter_food (name) values ('Soybean');
insert into poopreporter_food (name) values ('Ensure plus');
insert into poopreporter_food (name) values ('Vegetable and fruit juice drink');
insert into poopreporter_food (name) values ('Chicken');
insert into poopreporter_food (name) values ('Olive loaf');
insert into poopreporter_food (name) values ('Whipped cream substitute');
insert into poopreporter_food (name) values ('Prickly pears');
