insert into poopreporter_neighborhood (name) values ('North Seattle');
insert into poopreporter_neighborhood (name) values ('Broadview');
insert into poopreporter_neighborhood (name) values ('Bitter Lake');
insert into poopreporter_neighborhood (name) values ('North Beach/Blue Ridge');
insert into poopreporter_neighborhood (name) values ('Crown Hill');
insert into poopreporter_neighborhood (name) values ('Greenwood');
insert into poopreporter_neighborhood (name) values ('Northgate');
insert into poopreporter_neighborhood (name) values ('Haller Lake');
insert into poopreporter_neighborhood (name) values ('Pinehurst');
insert into poopreporter_neighborhood (name) values ('North College Park');
insert into poopreporter_neighborhood (name) values ('Maple Leaf');
insert into poopreporter_neighborhood (name) values ('Lake City');
insert into poopreporter_neighborhood (name) values ('Cedar Park');
insert into poopreporter_neighborhood (name) values ('Matthews Beach');
insert into poopreporter_neighborhood (name) values ('Meadowbrook');
insert into poopreporter_neighborhood (name) values ('Olympic Hills');
insert into poopreporter_neighborhood (name) values ('Victory Heights');
insert into poopreporter_neighborhood (name) values ('Wedgwood');
insert into poopreporter_neighborhood (name) values ('View Ridge');
insert into poopreporter_neighborhood (name) values ('Sand Point');
insert into poopreporter_neighborhood (name) values ('Roosevelt');
insert into poopreporter_neighborhood (name) values ('Ravenna');
insert into poopreporter_neighborhood (name) values ('Bryant');
insert into poopreporter_neighborhood (name) values ('Windermere');
insert into poopreporter_neighborhood (name) values ('Hawthorne Hills');
insert into poopreporter_neighborhood (name) values ('Laurelhurst');
insert into poopreporter_neighborhood (name) values ('University District ("U. District")');
insert into poopreporter_neighborhood (name) values ('University Village');
insert into poopreporter_neighborhood (name) values ('Wallingford');
insert into poopreporter_neighborhood (name) values ('Northlake');
insert into poopreporter_neighborhood (name) values ('Fremont');
insert into poopreporter_neighborhood (name) values ('Phinney Ridge');
insert into poopreporter_neighborhood (name) values ('Ballard');
insert into poopreporter_neighborhood (name) values ('West Woodland');
insert into poopreporter_neighborhood (name) values ('Whittier Heights');
insert into poopreporter_neighborhood (name) values ('Adams');
insert into poopreporter_neighborhood (name) values ('Sunset Hill');
insert into poopreporter_neighborhood (name) values ('Loyal Heights');
insert into poopreporter_neighborhood (name) values ('Central Seattle');
insert into poopreporter_neighborhood (name) values ('Magnolia');
insert into poopreporter_neighborhood (name) values ('Lawton Park');
insert into poopreporter_neighborhood (name) values ('Briarcliff');
insert into poopreporter_neighborhood (name) values ('Southeast Magnolia');
insert into poopreporter_neighborhood (name) values ('Interbay');
insert into poopreporter_neighborhood (name) values ('Queen Anne');
insert into poopreporter_neighborhood (name) values ('North Queen Anne');
insert into poopreporter_neighborhood (name) values ('East Queen Anne');
insert into poopreporter_neighborhood (name) values ('Lower Queen Anne');
insert into poopreporter_neighborhood (name) values ('West Queen Anne');
insert into poopreporter_neighborhood (name) values ('Capitol Hill');
insert into poopreporter_neighborhood (name) values ('Portage Bay / Roanoke');
insert into poopreporter_neighborhood (name) values ('Broadway');
insert into poopreporter_neighborhood (name) values ('Pike-Pine Corridor / Pike/Pine');
insert into poopreporter_neighborhood (name) values ('Montlake');
insert into poopreporter_neighborhood (name) values ('Stevens');
insert into poopreporter_neighborhood (name) values ('Interlaken');
insert into poopreporter_neighborhood (name) values ('Madison Valley');
insert into poopreporter_neighborhood (name) values ('Renton Hill');
insert into poopreporter_neighborhood (name) values ('Madison Park');
insert into poopreporter_neighborhood (name) values ('Broadmoor');
insert into poopreporter_neighborhood (name) values ('Lake Union');
insert into poopreporter_neighborhood (name) values ('South Lake Union, Seattle');
insert into poopreporter_neighborhood (name) values ('Cascade, Seattle');
insert into poopreporter_neighborhood (name) values ('Westlake');
insert into poopreporter_neighborhood (name) values ('Eastlake');
insert into poopreporter_neighborhood (name) values ('Downtown');
insert into poopreporter_neighborhood (name) values ('Denny Regrade');
insert into poopreporter_neighborhood (name) values ('Belltown');
insert into poopreporter_neighborhood (name) values ('Pike-Market');
insert into poopreporter_neighborhood (name) values ('Central Business District');
insert into poopreporter_neighborhood (name) values ('First Hill');
insert into poopreporter_neighborhood (name) values ('Pioneer Square');
insert into poopreporter_neighborhood (name) values ('International District ("ID")');
insert into poopreporter_neighborhood (name) values ('Yesler Terrace');
insert into poopreporter_neighborhood (name) values ('Central Waterfront');
insert into poopreporter_neighborhood (name) values ('West Edge');
insert into poopreporter_neighborhood (name) values ('Central Area / Central District ("CD")');
insert into poopreporter_neighborhood (name) values ('Mann');
insert into poopreporter_neighborhood (name) values ('Minor');
insert into poopreporter_neighborhood (name) values ('Cherry Hill & Squire Park');
insert into poopreporter_neighborhood (name) values ('Atlantic');
insert into poopreporter_neighborhood (name) values ('Judkins Park');
insert into poopreporter_neighborhood (name) values ('Madrona');
insert into poopreporter_neighborhood (name) values ('Madrona Valley');
insert into poopreporter_neighborhood (name) values ('Harrison / Denny-Blaine');
insert into poopreporter_neighborhood (name) values ('Washington Park');
insert into poopreporter_neighborhood (name) values ('Leschi');
insert into poopreporter_neighborhood (name) values ('South End');
insert into poopreporter_neighborhood (name) values ('Rainier Valley');
insert into poopreporter_neighborhood (name) values ('Mount Baker');
insert into poopreporter_neighborhood (name) values ('Columbia City');
insert into poopreporter_neighborhood (name) values ('Hillman City');
insert into poopreporter_neighborhood (name) values ('Brighton');
insert into poopreporter_neighborhood (name) values ('Dunlap / Othello');
insert into poopreporter_neighborhood (name) values ('Rainier Beach / Atlantic City Beach');
insert into poopreporter_neighborhood (name) values ('Rainier View / Lakeridge');
insert into poopreporter_neighborhood (name) values ('Seward Park');
insert into poopreporter_neighborhood (name) values ('Lakewood');
insert into poopreporter_neighborhood (name) values ('Beacon Hill');
insert into poopreporter_neighborhood (name) values ('North Beacon Hill');
insert into poopreporter_neighborhood (name) values ('Mid Beacon Hill (Maplewood)');
insert into poopreporter_neighborhood (name) values ('Holly Park / NewHolly');
insert into poopreporter_neighborhood (name) values ('South Beacon Hill / Van Asselt');
insert into poopreporter_neighborhood (name) values ('Industrial District');
insert into poopreporter_neighborhood (name) values ('SoDo');
insert into poopreporter_neighborhood (name) values ('Harbor Island');
insert into poopreporter_neighborhood (name) values ('Georgetown');
insert into poopreporter_neighborhood (name) values ('South Park');
insert into poopreporter_neighborhood (name) values ('West Seattle');
insert into poopreporter_neighborhood (name) values ('Alki Point');
insert into poopreporter_neighborhood (name) values ('North Admiral / Admiral District');
insert into poopreporter_neighborhood (name) values ('Junction / West Seattle Junction / Alaska Junction');
insert into poopreporter_neighborhood (name) values ('Seaview / Mee-Kwa-Mooks');
insert into poopreporter_neighborhood (name) values ('Fairmount Park');
insert into poopreporter_neighborhood (name) values ('Genesee');
insert into poopreporter_neighborhood (name) values ('Gatewood');
insert into poopreporter_neighborhood (name) values ('Fauntleroy');
insert into poopreporter_neighborhood (name) values ('Arbor Heights');
insert into poopreporter_neighborhood (name) values ('Delridge');
insert into poopreporter_neighborhood (name) values ('North Delridge');
insert into poopreporter_neighborhood (name) values ('Pigeon Point');
insert into poopreporter_neighborhood (name) values ('Riverview');
insert into poopreporter_neighborhood (name) values ('Highland Park');
insert into poopreporter_neighborhood (name) values ('South Delridge');
insert into poopreporter_neighborhood (name) values ('Roxhill');
insert into poopreporter_neighborhood (name) values ('High Point');
