insert into poopreporter_symptom (name) values ('Diarrhea');
insert into poopreporter_symptom (name) values ('Vomiting');
insert into poopreporter_symptom (name) values ('Abdominal Cramps');
insert into poopreporter_symptom (name) values ('Nausea');
insert into poopreporter_symptom (name) values ('Fever');
insert into poopreporter_symptom (name) values ('Joint/back aches');
insert into poopreporter_symptom (name) values ('Fatigue');
insert into poopreporter_symptom (name) values ('Headache');
insert into poopreporter_symptom (name) values ('Sneezing');
insert into poopreporter_symptom (name) values ('Cough');
insert into poopreporter_symptom (name) values ('Sore Throat');
insert into poopreporter_symptom (name) values ('Nasal Congestion');
insert into poopreporter_symptom (name) values ('Runny Nose');
insert into poopreporter_symptom (name) values ('Decreased Appetite');
insert into poopreporter_symptom (name) values ('Stomach Ache');
insert into poopreporter_symptom (name) values ('Chills');
